### ISSUE TITLE
hook看起来效果不好

### ISSUE THREAD

**Issue by suxinwei** [PTrainbow/NativeBitmap#1]
这个库很棒哈，不过用在demo上profile内存，每次新建bitmap看起来都是java内存在增加。作者有联系方式方便加下不

**Comment by PTrainbow** [comment]
> 这个库很棒哈，不过用在demo上profile内存，每次新建bitmap看起来都是java内存在增加。作者有联系方式方便加下不

@suxinwei 可能是没 hook 成功么？可以呀

**Comment by PTrainbow** [comment]
@suxinwei 327365600@qq.com, njuptrain@gmail.com
