### ISSUE TITLE
模拟器是不支持的

### ISSUE THREAD

**Issue by kiddot** [PTrainbow/NativeBitmap#3]
shadowhook的实现是对模拟器x86的架构不太支持的。作者有没有试过用bytehook来实现？我发现bytehook的方式在模拟器完全hook不到

**Comment by PTrainbow** [comment]
> shadowhook的实现是对模拟器x86的架构不太支持的。作者有没有试过用bytehook来实现？我发现bytehook的方式在模拟器完全hook不到

@kiddot bytehook hook不到一些内部方法
