### ISSUE TITLE
大部分bitmap的识别失败了

### ISSUE THREAD

**Issue by ailichao** [PTrainbow/NativeBitmap#4]
设备：android 7.1
hook结果ok，但使用glide加载20张bitmap，只有一张识别到了：

![EC5AE5B5-F1B3-4893-80C3-6F851D5FB3A9](https://github.com/PTrainbow/NativeBitmap/assets/6703008/09009efc-8e6d-460e-8f86-85666e11dc35)

预期是否应该有20次"native bitmap malloc size"的打印？
<img width="689" alt="image" src="https://github.com/PTrainbow/NativeBitmap/assets/6703008/ad23552d-9057-468b-a119-80511b77cc8d">

**Comment by PTrainbow** [comment]
> 设备：android 7.1 hook结果ok，但使用glide加载20张bitmap，只有一张识别到了：
> 
> ![EC5AE5B5-F1B3-4893-80C3-6F851D5FB3A9](https://user-images.githubusercontent.com/6703008/255115709-09009efc-8e6d-460e-8f86-85666e11dc35.png)
> 
> 预期是否应该有20次"native bitmap malloc size"的打印？ <img alt="image" width="689" src="https://user-images.githubusercontent.com/6703008/255116891-ad23552d-9057-468b-a119-80511b77cc8d.png">

fix/java_pixel_ref_symbol 这个分支尝试一下呢？

**Comment by PTrainbow** [comment]
https://github.com/PTrainbow/NativeBitmap/pull/5

可以看看这个 pr，应该是之前这个符号漏改了
